"""update_task_executions_and_agent_artifacts

Revision ID: 76cacff5beb0
Revises: 2de756d9d4b6
Create Date: 2026-08-11 20:09:48.760836

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '76cacff5beb0'
down_revision: Union[str, Sequence[str], None] = '2de756d9d4b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Add columns as nullable or with defaults for existing rows
    op.add_column('agent_artifacts', sa.Column('task_id', sa.UUID(), nullable=True))
    op.execute("UPDATE agent_artifacts SET task_id = task_execution_id WHERE task_id IS NULL AND task_execution_id IS NOT NULL")
    op.execute("DELETE FROM agent_artifacts WHERE task_id IS NULL")
    op.alter_column('agent_artifacts', 'task_id', nullable=False)

    op.add_column('agent_artifacts', sa.Column('relative_path', sa.String(length=500), nullable=True))
    op.add_column('agent_artifacts', sa.Column('category', sa.String(length=100), nullable=False, server_default='docs'))
    op.add_column('agent_artifacts', sa.Column('version', sa.Integer(), nullable=False, server_default='1'))
    op.add_column('agent_artifacts', sa.Column('content_hash', sa.String(length=64), nullable=True))
    op.alter_column('agent_artifacts', 'task_execution_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.create_foreign_key(None, 'agent_artifacts', 'task_executions', ['task_id'], ['id'])

    op.add_column('task_executions', sa.Column('current_step', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('task_executions', sa.Column('total_steps', sa.Integer(), nullable=False, server_default='12'))
    op.add_column('task_executions', sa.Column('percentage_completed', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('task_executions', sa.Column('agents_completed', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('task_executions', sa.Column('agents_failed', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('task_executions', sa.Column('artifacts_generated', sa.Integer(), nullable=False, server_default='0'))



def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task_executions', 'artifacts_generated')
    op.drop_column('task_executions', 'agents_failed')
    op.drop_column('task_executions', 'agents_completed')
    op.drop_column('task_executions', 'percentage_completed')
    op.drop_column('task_executions', 'total_steps')
    op.drop_column('task_executions', 'current_step')
    op.drop_constraint(None, 'agent_artifacts', type_='foreignkey')
    op.alter_column('agent_artifacts', 'task_execution_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('agent_artifacts', 'content_hash')
    op.drop_column('agent_artifacts', 'version')
    op.drop_column('agent_artifacts', 'category')
    op.drop_column('agent_artifacts', 'relative_path')
    op.drop_column('agent_artifacts', 'task_id')
    # ### end Alembic commands ###
